language: cpp

sudo: false

arch:
    - amd64
    - arm64

matrix:
    include:
        - os: linux
        language: cpp
        script:
            - ls
            - cd cpp
            - mkdir build
            - cd build
            - cmake ..
            - make
            - ./gtest/all-gtest
        - os: linux
        language: python
        python:
            - "3.6"
        script:
            - ls
            - cd python/tests
            - python -m nose -v test.py

# matrix:
#   include:
#     - os: osx
#       osx_image: xcode10.2
#       addons:
#           homebrew:
#             packages:
#             - python
#             - zeromq
#             - msgpack
#             - cmake
#             - boost
#             update: true

# before_install:
#     - eval "${MATRIX_EVAL}"

# script:
#     - ls
#
# after_success:
#     - echo "yeah!!"


# notifications:
#   email: false
#   irc:
#     channels:
#     - chat.freenode.net#rubinius
#     template:
#     - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
