language: cpp
os: linux
dist: bionic
sudo: false

matrix:
    include:
        # - language: cpp
        #   addons:
        #       apt:
        #         packages:
        #           - cmake
        #           - libzmq3-dev
        #   arch:
        #       - amd64
        #       - arm64
        #   script:
        #     - ls
        #     - cd cpp
        #     - ./build_extlibs.sh
        #     - mkdir build
        #     - cd build
        #     - cmake ..
        #     - make
        #     - ls
        #     - ./gtests/all-gtest
        - language: python
          addons:
              apt:
                packages:
                  - cmake
                  - libzmq3-dev
                  - python3-dev
          python:
            - "3.6"
            - "3.7"
            # - "3.8"
          # virtualenv:
          #   system_site_packages: true
          script:
            - ls
            - cd python/tests
            - python -m nose -v test.py
          install:
            - ls
            - pip install -U pip setuptools wheel build_utils nose
            - pip install -e .

# matrix:
#   include:
#     - os: osx
#       osx_image: xcode10.2
#       addons:
#           homebrew:
#             packages:
#             - python
#             - zeromq
#             - msgpack
#             - cmake
#             - boost
#             update: true

# before_install:
#     - eval "${MATRIX_EVAL}"

# script:
#     - ls
#
# after_success:
#     - echo "yeah!!"


# notifications:
#   email: false
#   irc:
#     channels:
#     - chat.freenode.net#rubinius
#     template:
#     - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
