language: cpp
os: linux
sudo: false
arch:
    - amd64
    - arm64

matrix:
    include:
        - language: cpp
          script:
            - ls
            - cd cpp
            - mkdir build
            - cd build
            - cmake ..
            - make
            - ./gtest/all-gtest
        - language: python
          python:
            - "3.6"
            - "3.7"
            - "3.8"
          virtualenv:
            system_site_packages: true
          script:
            - ls
            - cd python/tests
            - python -m nose -v test.py

# matrix:
#   include:
#     - os: osx
#       osx_image: xcode10.2
#       addons:
#           homebrew:
#             packages:
#             - python
#             - zeromq
#             - msgpack
#             - cmake
#             - boost
#             update: true

# before_install:
#     - eval "${MATRIX_EVAL}"

# script:
#     - ls
#
# after_success:
#     - echo "yeah!!"


# notifications:
#   email: false
#   irc:
#     channels:
#     - chat.freenode.net#rubinius
#     template:
#     - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
