matrix:
    include:
        - name "linux c++"
        language: cpp
        os: linux
        arch:
            - amd64
            - arm64
        script:
            - ls
            - cd cpp
            - mkdir build
            - cd build
            - cmake ..
            - make
            - ./gtest/all-gtest
        - name "linux python"
        language: python
        os: linux
        arch:
            - amd64
            - arm64
        script:
            - ls
            - cd python/tests
            - python -m nose -v test.py

sudo: false
# matrix:
#   include:
#     - os: osx
#       osx_image: xcode10.2
#       addons:
#           homebrew:
#             packages:
#             - python
#             - zeromq
#             - msgpack
#             - cmake
#             - boost
#             update: true

# before_install:
#     - eval "${MATRIX_EVAL}"

# script:
#     - ls
#
# after_success:
#     - echo "yeah!!"


# notifications:
#   email: false
#   irc:
#     channels:
#     - chat.freenode.net#rubinius
#     template:
#     - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
