name: Cpp
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            # - name: Cache node modules
            #   uses: actions/cache@v1
            #   with:
            #     path: /opt/gecko
            #     key: ${{ runner.OS }}-build-extlibs
            #     restore-keys: |
            #       ${{ runner.OS }}-build-extlibs
            
            - name: Install dependencies
              run: |
                cd cpp
                chmod a+x *.sh
                ./build_extlibs.sh
            - name: Test gecko
              run: |
                mkdir -p cpp/build
                cd cpp/build
                cmake ..
                make
                ./gtests/all-gtest
